language: python
python:
  - '3.9'
install:
  - pip install -e .[dev]
  - pip install coveralls
before_script:
script: 
  - coverage run -m pytest -s --verbose
  - coveralls
after_success:
notifications:
  on_success: never
  on_failure: always
